[DEFAULT]
# All sections below are required unless otherwise specified.
# See https://github.com/AnswerDotAI/nbdev/blob/main/settings.ini for examples.

### Python library ###
repo = ddpm_backtest
lib_name = %(repo)s
version = 0.0.1
min_python = 3.9
license = apache2
black_formatting = False

### nbdev ###
doc_path = _docs
lib_path = ddpm_backtest
nbs_path = nbs
recursive = True
tst_flags = notest
put_version_in_init = True
update_pyproject = True

### Docs ###
branch = main
custom_sidebar = False
doc_host = https://%(user)s.github.io
doc_baseurl = /%(repo)s
git_url = https://github.com/%(user)s/%(repo)s
title = %(lib_name)s

### PyPI ###
audience = Developers
author = Garvit
author_email = garvitdhanwaria@gmail.com
copyright = 2026 onwards, %(author)s
description = DDPM-based financial risk model for generating market returns and estimating VaR
keywords = nbdev jupyter notebook python
language = English
status = 3
user = garvit

### Optional ###
requirements = numpy pandas torch tqdm scikit-learn hmmlearn arch
