# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto 0
__all__ = ['f_net', 'FiLMLayer']

# %% ../nbs/models.ipynb 1
import torch
import torch.nn as nn


# %% ../nbs/models.ipynb 2
def f_net(ni,nf,nfs=(256,512,1024,512,256,128)):
  layers = []
  layers.append(nn.Linear(ni, nfs[0]))
  layers.append(nn.SiLU())
  for i in range(len(nfs) - 1):
    layers.append(nn.Linear(nfs[i], nfs[i+1]))
    layers.append(nn.SiLU())
  layers.append(nn.Linear(nfs[-1], nf))

  return nn.Sequential(*layers)

# %% ../nbs/models.ipynb 3
class FiLMLayer(nn.Module):
    def __init__(self, hidden_dim, cond_dim):
        super().__init__()
        self.scale = nn.Linear(cond_dim, hidden_dim)
        self.shift = nn.Linear(cond_dim, hidden_dim)
        nn.init.zeros_(self.scale.weight)   
        nn.init.zeros_(self.shift.weight)   
        nn.init.ones_(self.scale.bias)      

    def forward(self, x, cond_emb):
        scale = self.scale(cond_emb)
        shift = self.shift(cond_emb)
        scale = 1 + torch.tanh(scale - 1)
        return x * scale + shift
