# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/generating_data.ipynb.

# %% auto 0
__all__ = ['sample_n_samples', 'sample_with_conditions']

# %% ../nbs/generating_data.ipynb 8
from tqdm.auto import tqdm
import torch
import torch.nn as nn
import numpy as np

# %% ../nbs/generating_data.ipynb 9
def sample_n_samples(
    n_samples, model, alphas, betas, scaler_x,
    guidance_scale_cat=1.5,
    guidance_scale_cont=0.5,
    null_label=0,
    regime=1,              
    continuous_cond=None, 
):
    global alphas_bar, T
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    alphas_t = torch.from_numpy(alphas).float().to(device)
    betas_t  = torch.from_numpy(betas).float().to(device)

    model.eval()
    model.to(device)

    xt = torch.randn((n_samples, 1), device=device)
    c_cond = torch.full((n_samples,), regime, device=device, dtype=torch.long)

    if continuous_cond is None:
        continuous_cond = torch.zeros((n_samples, 8), device=device, dtype=torch.float32)
    else:
        continuous_cond = continuous_cond.to(device).repeat(n_samples, 1)

    null_c    = torch.full_like(c_cond, null_label)
    null_cond = torch.zeros_like(continuous_cond)

    with torch.no_grad():
        for t in tqdm(reversed(range(T)), desc="Sampling", total=T):
            t_tensor = torch.full((n_samples,), t, device=device, dtype=torch.long)

            alpha_t      = alphas_t[t].unsqueeze(0).unsqueeze(1)
            beta_t       = betas_t[t].unsqueeze(0).unsqueeze(1)
            alpha_bar_t  = alphas_bar[t].unsqueeze(0).unsqueeze(1)

            sqrt_alpha_t             = torch.sqrt(alpha_t)
            sqrt_one_minus_alpha_bar = torch.sqrt(1.0 - alpha_bar_t)

            t_float = t_tensor.float()
            eps_uncond = model(xt, null_c,  null_cond,        t_float)
            eps_cat    = model(xt, c_cond,  null_cond,        t_float)
            eps_cont   = model(xt, null_c,  continuous_cond,  t_float)

            eps_guided = (
                eps_uncond
                + guidance_scale_cat  * (eps_cat  - eps_uncond)
                + guidance_scale_cont * (eps_cont - eps_uncond)
            )

            mean_t = (xt - (beta_t / sqrt_one_minus_alpha_bar) * eps_guided) / sqrt_alpha_t

            if t > 0:
                z  = torch.randn_like(xt)
                xt = mean_t + torch.sqrt(beta_t) * z
            else:
                xt = mean_t

    return scaler_x.inverse_transform(xt.cpu().numpy())

# %% ../nbs/generating_data.ipynb 10
def sample_with_conditions(
    condition_row, n_samples, model, alphas, betas, scaler_x, scaler_cond,
    # CFG params
    guidance_scale_cat=0.5,
    guidance_scale_cont=0.2,
    null_label=0,
    alphas_bar_in=None,  # pass explicitly to avoid stale global
    temperature=1,     # >1.0 widens distribution variance
):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    torch.manual_seed(42)
    np.random.seed(42)
    _ab = (alphas_bar_in if alphas_bar_in is not None else alphas_bar).to(device)

    alphas_t = torch.from_numpy(alphas).float().to(device)
    betas_t  = torch.from_numpy(betas).float().to(device)

    model.eval()
    model.to(device)

    xt = torch.randn((n_samples, 1), device=device)

    print(f"Sampling with REAL conditions:")
    print(f"  Regime: {condition_row['regime']}")
    print(f"  Regime: {condition_row['regime']}")
    print(f"  Realized Vol: {condition_row['realized_vol']:.4f}")
    print(f"  VIX: {condition_row['VIX']:.2f}")
    print(f"  RSI: {condition_row['RSI']:.2f}")
    print(f"  Skew: {condition_row['skew']:.3f}")
    print(f"  guidance_scale_cat={guidance_scale_cat}, guidance_scale_cont={guidance_scale_cont}")

    # --- Conditions ---
    regime = int(condition_row['regime'])
    c_cond = torch.full((n_samples,), regime+1, device=device, dtype=torch.long)

    continuous_features = np.array([
        condition_row['realized_vol'],
        condition_row['VIX'],
        condition_row['RSI'],
        condition_row['skew'],
        condition_row['kurtosis'],
        condition_row['vol_spike'],
        condition_row['RSI_velocity'],
        condition_row['regime_score']
    ]).reshape(1, -1)

    continuous_features_scaled = scaler_cond.transform(continuous_features)
    continuous_cond = torch.tensor(
        continuous_features_scaled, device=device, dtype=torch.float32
    ).repeat(n_samples, 1)

    # --- Null tensors (defined once, reused every step) ---
    null_c    = torch.full_like(c_cond, null_label)
    null_cond = torch.zeros_like(continuous_cond)

    # --- Reverse diffusion ---
    with torch.no_grad():
        for t in tqdm(reversed(range(T)), desc="Sampling", total=T):
            t_tensor = torch.full((n_samples,), t, device=device, dtype=torch.long)

            alpha_t       = alphas_t[t].unsqueeze(0).unsqueeze(1)
            beta_t        = betas_t[t].unsqueeze(0).unsqueeze(1)
            alpha_bar_t   = _ab[t].unsqueeze(0).unsqueeze(1)

            sqrt_alpha_t             = torch.sqrt(alpha_t)
            sqrt_one_minus_alpha_bar = torch.sqrt(1. - alpha_bar_t).clamp(min=1e-5)

            # --- CFG: 3 forward passes ---
            t_float = t_tensor.float()
            eps_uncond = model(xt, null_c,  null_cond,       t_float)  # neither
            eps_cat    = model(xt, c_cond,  null_cond,       t_float)  # only regime
            eps_cont   = model(xt, null_c,  continuous_cond, t_float)  # only continuous

            eps_guided = (
                eps_uncond
                + guidance_scale_cat  * (eps_cat  - eps_uncond)
                + guidance_scale_cont * (eps_cont - eps_uncond)
            ).clamp(-3.0, 3.0)
            # --- Reverse step ---
            mean_t = (xt - (beta_t / sqrt_one_minus_alpha_bar) * eps_guided) / sqrt_alpha_t

            if t > 0:
                z  = torch.randn_like(xt)
                xt = mean_t + temperature * torch.sqrt(beta_t) * z
                xt = xt.clamp(-10.0, 10.0)  # prevent runaway values
            else:
                xt = mean_t

    return scaler_x.inverse_transform(xt.cpu().numpy())

