# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/VaR_ES.ipynb.

# %% auto 0
__all__ = ['actual_regime0_returns', 'risk_comparison']

# %% ../nbs/VaR_ES.ipynb 9
from scipy import stats

def risk_comparison(generated_samples, actual_returns, confidence_levels=[0.95, 0.99]):
    gen = generated_samples.flatten()
    act = actual_returns.flatten()
    print(f"{'Metric':<25} {'Generated':>12} {'Actual':>12} {'Error%':>10}")
    print('-' * 62)
    for cl in confidence_levels:
        var_gen = np.percentile(gen, (1 - cl) * 100)
        var_act = np.percentile(act, (1 - cl) * 100)
        err     = (var_gen - var_act) / abs(var_act) * 100
        print(f"VaR  {cl:.0%}            {var_gen:>12.6f} {var_act:>12.6f} {err:>9.1f}%")
        cvar_gen = gen[gen <= var_gen].mean()
        cvar_act = act[act <= var_act].mean()
        err      = (cvar_gen - cvar_act) / abs(cvar_act) * 100
        print(f"CVaR {cl:.0%}            {cvar_gen:>12.6f} {cvar_act:>12.6f} {err:>9.1f}%")
    print(f"\n{'min':<25} {gen.min():>12.6f} {act.min():>12.6f} {(gen.min()-act.min())/abs(act.min())*100:>9.1f}%")
    print(f"{'1st percentile':<25} {np.percentile(gen,1):>12.6f} {np.percentile(act,1):>12.6f} {(np.percentile(gen,1)-np.percentile(act,1))/abs(np.percentile(act,1))*100:>9.1f}%")
    print(f"{'5th percentile':<25} {np.percentile(gen,5):>12.6f} {np.percentile(act,5):>12.6f} {(np.percentile(gen,5)-np.percentile(act,5))/abs(np.percentile(act,5))*100:>9.1f}%")
    print('\nTarget: VaR error < 10% = production grade, < 20% = acceptable')

actual_regime0_returns = condition_df[condition_df['regime'] == 0]['target_return'].dropna().values
risk_comparison(generated_samples, actual_regime0_returns)
