# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/abalation.ipynb.

# %% auto 0
__all__ = ['condition_row', 'samples_real', 'samples_zero', 'sample_with_ablation', 'compare_conditioning_ablation']

# %% ../nbs/abalation.ipynb 5
from scipy import stats
import matplotlib.pyplot as plt
def sample_with_ablation(
    condition_row,
    n_samples,
    model,
    alphas,
    betas,
    alphas_bar,
    scaler_x,
    scaler_cond,
    guidance_scale_cat = 2.5,
    guidance_scale_cont = 1.5,
    zero_continuous=False,   
    seed=42,
):

    global T   

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    alphas_t   = torch.from_numpy(alphas).float().to(device)
    betas_t    = torch.from_numpy(betas).float().to(device)
    alphas_bar = alphas_bar.to(device)

    model.eval()
    model.to(device)

    torch.manual_seed(seed)
    xt = torch.randn((n_samples, 1), device=device)
    regime  = int(condition_row['regime'])
    c_cond  = torch.full((n_samples,), regime + 1, device=device, dtype=torch.long)
    cont_feature_names = ['realized_vol', 'VIX', 'RSI', 'skew', 'kurtosis', 'vol_spike', 'RSI_velocity', 'regime_score']

    if zero_continuous:
        continuous_cond = torch.zeros((n_samples, 8), device=device, dtype=torch.float32)
        label = "Zeroed Continuous (ablation)"
    else:
        raw_values = np.array([condition_row[f] for f in cont_feature_names]).reshape(1, -1)
        scaled_values = scaler_cond.transform(raw_values)
        continuous_cond = torch.tensor(scaled_values, dtype=torch.float32, device=device).repeat(n_samples, 1)
        label = "Real Continuous Conditioning"
    null_c = torch.full_like(c_cond,0)
    null_cond = torch.zeros_like(continuous_cond)

    print(f"\n[{label}]  regime={regime}, n_samples={n_samples}")

    
    with torch.no_grad():
        for t in tqdm(reversed(range(T)), desc=f"Sampling ({label[:4]}…)", total=T, leave=False):
            t_tensor = torch.full((n_samples,), t, device=device, dtype=torch.long)

            alpha_t      = alphas_t[t].unsqueeze(0).unsqueeze(1)
            beta_t       = betas_t[t].unsqueeze(0).unsqueeze(1)
            alpha_bar_t  = alphas_bar[t].unsqueeze(0).unsqueeze(1)

            sqrt_alpha_t             = torch.sqrt(alpha_t)
            sqrt_one_minus_alpha_bar = torch.sqrt(1.0 - alpha_bar_t)

            t_float = t_tensor.float()
            eps_uncond = model(xt,null_c,null_cond,t_float)
            eps_cat = model(xt,c_cond,null_cond,t_float)
            eps_hat = model(xt, null_c, continuous_cond, t_tensor.float())
            eps_guided = (eps_uncond  + guidance_scale_cat * (eps_cat - eps_uncond) + guidance_scale_cont * (eps_hat - eps_uncond)).clamp(-3,3)
            mean_t = (xt - (beta_t / sqrt_one_minus_alpha_bar) * eps_guided) / sqrt_alpha_t

            if t > 0:
                torch.manual_seed(seed + t)   
                z  = torch.randn_like(xt)
                xt = mean_t + torch.sqrt(beta_t) * z
                xt = xt.clamp(-10.0,10.0)
            else:
                xt = mean_t

    return scaler_x.inverse_transform(xt.cpu().numpy())



def compare_conditioning_ablation(
    condition_row,
    val_df_orig,         
    n_samples,
    model,
    alphas,
    betas,
    alphas_bar,
    scaler_x,
    scaler_cond,
    guidance_scale_cat = 2.5,
    guidance_scale_cont = 1.5,
    regime_to_check=0,
):

    samples_real  = sample_with_ablation(
        condition_row, n_samples, model, alphas, betas, alphas_bar,
        scaler_x, scaler_cond, guidance_scale_cat = 2.5,guidance_scale_cont = 1.5,zero_continuous=False
    ).flatten()

    samples_zero  = sample_with_ablation(
        condition_row, n_samples, model, alphas, betas, alphas_bar,
        scaler_x, scaler_cond, guidance_scale_cat = 2.5,guidance_scale_cont = 1.5,zero_continuous=True
    ).flatten()

    actual_returns = val_df_orig[val_df_orig['regime'] == regime_to_check]['target_return'].dropna().values

    def describe(arr, name):
        print(f"\n  {name}:")
        print(f"    mean={arr.mean():.6f}  std={arr.std():.6f}  "
              f"skew={stats.skew(arr):.3f}  kurt={stats.kurtosis(arr):.3f}")

    print("\n─── Distribution Statistics ───")
    describe(samples_real,  "Generated (Real Continuous)")
    describe(samples_zero,  "Generated (Zero Continuous)")
    describe(actual_returns, f"Actual Val Regime {regime_to_check}")

    ks_real_vs_zero = stats.ks_2samp(samples_real, samples_zero)
    ks_real_vs_actual = stats.ks_2samp(samples_real, actual_returns)
    ks_zero_vs_actual = stats.ks_2samp(samples_zero, actual_returns)

    print("\n─── KS Tests (higher statistic = more different) ───")
    print(f"  Real vs Zero conditioning : stat={ks_real_vs_zero.statistic:.4f},   p={ks_real_vs_zero.pvalue:.4f}")
    print(f"  Real vs Actual            : stat={ks_real_vs_actual.statistic:.4f},   p={ks_real_vs_actual.pvalue:.4f}")
    print(f"  Zero vs Actual            : stat={ks_zero_vs_actual.statistic:.4f},   p={ks_zero_vs_actual.pvalue:.4f}")

    if ks_real_vs_zero.pvalue > 0.05:
        print("\n  [Warning] Real and Zero distributions are NOT significantly different (p > 0.05).")
        print("     → Continuous conditioning may not be having a meaningful effect on the model.")
    else:
        print("\n  [Success] Real and Zero distributions ARE significantly different (p < 0.05).")
        print("     → Continuous conditioning is influencing the generated samples.")

    
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle(
        f"Continuous Conditioning Ablation — Regime {regime_to_check}\n"
        f"(condition row: {condition_row.name})",
        fontsize=13, fontweight='bold'
    )

    bins = 60

    ax = axes[0]
    ax.hist(actual_returns,  bins=bins, density=True, alpha=0.45, color='orange', label='Actual Val Returns')
    ax.hist(samples_real,    bins=bins, density=True, alpha=0.45, color='steelblue', label='Generated (Real Cond.)')
    ax.hist(samples_zero,    bins=bins, density=True, alpha=0.45, color='tomato',  label='Generated (Zero Cond.)')
    ax.set_title("Histogram Overlay")
    ax.set_xlabel("Log Return")
    ax.set_ylabel("Density")
    ax.legend()
    ax.grid(True, alpha=0.3)

    ax = axes[1]
    from scipy.stats import gaussian_kde
    for arr, color, lbl in [
        (actual_returns, 'orange',    'Actual Val Returns'),
        (samples_real,   'steelblue', 'Generated (Real Cond.)'),
        (samples_zero,   'tomato',    'Generated (Zero Cond.)'),
    ]:
        arr_clean = arr[np.isfinite(arr)]
        if len(arr_clean) > 1:
            kde = gaussian_kde(arr_clean)
            xs  = np.linspace(arr_clean.min(), arr_clean.max(), 500)
            ax.plot(xs, kde(xs), color=color, lw=2, label=lbl)
    ax.set_title("KDE Shape Comparison")
    ax.set_xlabel("Log Return")
    ax.set_ylabel("Density")
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

    return samples_real, samples_zero




condition_row = condition_df[condition_df['regime'] == 0].iloc[-1]

samples_real, samples_zero = compare_conditioning_ablation(
    condition_row  = condition_row,
    val_df_orig    = condition_df,    
    n_samples      = 1000,
    model          = diffusion_model,
    alphas         = alphas,
    betas          = betas,
    alphas_bar     = alphas_bar,
    scaler_x       = scaler_x,
    scaler_cond    = scaler_cond,
    guidance_scale_cat = 1.5,
    guidance_scale_cont = 1.0,
    regime_to_check= 0,
)
