# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/complete_implementation_with_kupeic_and_christoffersen.ipynb.

# %% auto 0
__all__ = ['generate_path_ensemble_garch_with_breach_scaling', 'christoffersen_test', 'run_dqa']

# %% ../nbs/complete_implementation_with_kupeic_and_christoffersen.ipynb 12
def generate_path_ensemble_garch_with_breach_scaling(
    condition_df, n_paths, model, alphas, betas,
    scaler_x, scaler_cond, quantile_map=None,
    guidance_scale=1.5, temperature=1.0,
    alphas_bar_in=None, breach_scale=1.2,   
    n_diffusion_steps=100, scaled_cont_cols=None, unscaled_cont_cols=None, T=100
):
    T_eval   = len(condition_df)
    paths    = np.zeros((T_eval, n_paths))
    actual   = condition_df["target_return"].values
    prev_breach = False   

    for row_idx, (_, row) in enumerate(tqdm(condition_df.iterrows(),
                                             total=T_eval)):
        residuals = sample_residuals(
            row, n_paths, model, alphas, betas, scaler_x, scaler_cond,
            quantile_map=quantile_map,
            guidance_scale=guidance_scale,
            alphas_bar_in=alphas_bar_in,
            temperature=temperature,
            scaled_cont_cols=scaled_cont_cols,
            unscaled_cont_cols=unscaled_cont_cols,
            T=T
        )
        garch_vol = row["garch_vol"]
        effective_scale = breach_scale if prev_breach else 1.0
        paths[row_idx] = residuals * garch_vol * effective_scale
        var_95_today = np.percentile(paths[row_idx], 5)
        prev_breach  = actual[row_idx] < var_95_today

    actual = condition_df["target_return"].values
    var_95  = np.percentile(paths, 5,  axis=1)
    var_99  = np.percentile(paths, 1,  axis=1)
    es_95   = np.array([
        paths[i][paths[i] < var_95[i]].mean()
        if (paths[i] < var_95[i]).any() else var_95[i]
        for i in range(T_eval)
    ])
    es_99   = np.array([
        paths[i][paths[i] < var_99[i]].mean()
        if (paths[i] < var_99[i]).any() else var_99[i]
        for i in range(T_eval)
    ])

    print(f"\nGARCH-DDPM Ensemble with breach scaling ({T_eval} steps):")
    print(f"  VaR 95% breach rate: {(actual < var_95).mean():.3f}  (target 0.050)")
    print(f"  VaR 99% breach rate: {(actual < var_99).mean():.3f}  (target 0.010)")
    return paths, var_95, var_99, es_95, es_99

# %% ../nbs/complete_implementation_with_kupeic_and_christoffersen.ipynb 14
from scipy import stats
def christoffersen_test(actual_returns,var,alpha=0.05):
  hits = (actual_returns < var).astype(int)
  T = len(hits)
  N = hits.sum()
  prev = hits[:-1]
  curr = hits[1:]
  n_00 = ((prev == 0) & (curr == 0)).sum()
  n_01 = ((prev == 0) & (curr == 1)).sum()
  n_10 = ((prev == 1) & (curr == 0)).sum()
  n_11 = ((prev == 1) & (curr == 1)).sum()
  pi_01 = n_01 / (n_00 + n_01) if (n_00  + n_01) > 0 else 0.0
  pi_11 = n_11 / (n_10 + n_11) if(n_10 + n_11) > 0 else 0.0
  pi = N/T
  print(f"\nTransition probabilities:")
  print(f"  π_01={pi_01:.4f}  (P(breach | no breach yesterday))")
  print(f"  π_11={pi_11:.4f}  (P(breach | breach yesterday))")
  print(f"  π   ={pi:.4f}   (unconditional breach rate, target={alpha})")

  if N == 0 or N == T:
    lr_pof = -2 * (T * np.log(1-alpha) + 0 if N == 0 else T * np.log(alpha))
  else:
    lr_pof = -2 * (N * np.log(alpha) + (T - N)*np.log(1-alpha) - N *np.log(pi) -  (T - N) * np.log(1 - pi))
  def safe_log(x):
    return np.log(x) if x > 0 else 0.0
  l1_h0 =  ((n_00 + n_10)*safe_log(1-pi) + (n_01 + n_11)*safe_log(pi))
  ll_h1 = (
        n_00 * safe_log(1 - pi_01) +
        n_01 * safe_log(pi_01)     +
        n_10 * safe_log(1 - pi_11) +
        n_11 * safe_log(pi_11)
    )



  lr_ind = -2 * (l1_h0 - ll_h1)
  lr_cc = lr_pof + lr_ind
  p_pof = 1 - stats.chi2.cdf(lr_pof, df=1)
  p_ind = 1 - stats.chi2.cdf(lr_ind, df=1)
  p_cc  = 1 - stats.chi2.cdf(lr_cc,  df=2)
  print(f"\n{'='*55}")
  print(f" CHRISTOFFERSEN CONDITIONAL COVERAGE TEST")
  print(f"{'='*55}")
  print(f"  {'Test':<30} {'Stat':>8} {'df':>4} {'p-val':>8} {'Status':>8}")
  print(f"  {'-'*55}")

  for name, stat, df, pval in [
      ("Kupiec POF (coverage)",    lr_pof, 1, p_pof),
      ("Independence (clustering)",lr_ind, 1, p_ind),
      ("Conditional Coverage (CC)",lr_cc,  2, p_cc),
  ]:
    status = "PASS ✓" if pval >= 0.05 else "FAIL ✗"
    print(f"  {name:<30} {stat:>8.4f} {df:>4} {pval:>8.4f} {status:>8}")

  print(f"\n  Clustering ratio π_11/π_01: "
          f"{pi_11/pi_01:.3f}  (1.0 = no clustering, >2.0 = strong clustering)"
          if pi_01 > 0 else "  Cannot compute ratio (π_01=0)")

  return {
        "hits": hits, "T": T, "N": N,
        "n_00": n_00, "n_01": n_01, "n_10": n_10, "n_11": n_11,
        "pi_01": pi_01, "pi_11": pi_11, "pi": pi,
        "lr_pof": lr_pof, "lr_ind": lr_ind, "lr_cc": lr_cc,
        "p_pof": p_pof, "p_ind": p_ind, "p_cc": p_cc,
    }


# %% ../nbs/complete_implementation_with_kupeic_and_christoffersen.ipynb 15
import statsmodels.api as sm
import pandas as pd
def run_dqa(h,lags=4,var=None):
  df = pd.DataFrame({'hit': h})
  for i in range(1,lags + 1):
    df[f'lag_{i}'] = df['hit'].shift(i)
  if var is not None:
    df['var'] = var
  df = df.dropna()
  y = df['hit']
  X = df.drop(columns=['hit'])
  X = sm.add_constant(X)
  model = sm.OLS(y,X)
  results = model.fit()
  terms_to_test = ['const = 0'] + [f'lag_{i} = 0' for i in range(1,lags  + 1)]
  if var is not None:
    terms_to_test.append('var = 0')
  hypothesis = ', '.join(terms_to_test)
  wald_test = results.wald_test(hypothesis,scalar=True)
  p_value = float(wald_test.pvalue)
  return {
        'Test Statistic': round(float(wald_test.statistic), 4),
        'p-value': round(p_value, 6),
        'Reject Null': p_value < 0.05,
        'Regression Summary': results.summary()
    }
