# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/VaR_ES.ipynb.

# %% auto 0
__all__ = ['actual_regime0_returns', 'risk_comparison']

# %% ../nbs/VaR_ES.ipynb 8
from scipy import stats

def _pct_error(gen_val, act_val):
    """Signed percentage error, robust to near-zero denominators."""
    denom = abs(act_val) if abs(act_val) > 1e-8 else 1e-8
    return (gen_val - act_val) / denom * 100

def risk_comparison(generated_samples, actual_returns, confidence_levels=[0.95, 0.99]):
    gen = generated_samples.flatten()
    act = actual_returns.flatten()

    print(f"{'Metric':<25} {'Generated':>12} {'Actual':>12} {'Error%':>10}")
    print('-' * 62)

    for cl in confidence_levels:
        var_gen = np.percentile(gen, (1 - cl) * 100)
        var_act = np.percentile(act, (1 - cl) * 100)
        print(f"VaR  {cl:.0%}            {var_gen:>12.6f} {var_act:>12.6f} {_pct_error(var_gen, var_act):>9.1f}%")

        cvar_gen = gen[gen <= var_gen].mean()
        cvar_act = act[act <= var_act].mean()
        print(f"CVaR {cl:.0%}            {cvar_gen:>12.6f} {cvar_act:>12.6f} {_pct_error(cvar_gen, cvar_act):>9.1f}%")

    print()
    for p in [1, 5]:
        pg, pa = np.percentile(gen, p), np.percentile(act, p)
        print(f"{'%dth percentile' % p:<25} {pg:>12.6f} {pa:>12.6f} {_pct_error(pg, pa):>9.1f}%")

    print('\nTarget: VaR error < 10% = production grade, < 20% = acceptable')
actual_regime0_returns = condition_df[condition_df['regime'] == 0]['target_return'].dropna().values
risk_comparison(generated_samples, actual_regime0_returns)
